# Generated by Django 6.0.7 on 2026-07-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentsubject_student_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='session_type',
            field=models.CharField(choices=[('محاضرة', 'LEC'), ('سيكشن', 'SEC')], max_length=7),
        ),
    ]
