# Generated by Django 6.0.7 on 2026-07-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentsubject_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='session_type',
            field=models.CharField(choices=[('محاضرة', 'Lecture'), ('سيكشن', 'Section')], max_length=7),
        ),
        migrations.DeleteModel(
            name='ExamCommittee',
        ),
    ]
