# Generated by Django 6.0.7 on 2026-07-18 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_delete_schedule'),
        ('students', '0004_student_department_examcommittee'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_num', models.PositiveSmallIntegerField(blank=True, help_text='رقم المجموعه', null=True)),
                ('session_type', models.CharField(choices=[('LEC', 'محاضرة'), ('SEC', 'سيكشن')], max_length=3)),
                ('day', models.CharField(choices=[('السبت', 'Saturday'), ('الاحد', 'Sunday'), ('الاثنين', 'Monday'), ('الثلاثاء', 'Tuesday'), ('الاربعاء', 'Wednesday'), ('الخميس', 'Thursday')], max_length=20)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='academic.staffmember')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='students', through='students.StudentSubject', to='academic.subject'),
        ),
    ]
