import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import Header from './components/header/header';
import Footer from './components/footer';
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "CIS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ar"
      dir='rtl'
      className='h-full antialiased'
    >
      <body className="min-h-full flex flex-col">
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <Header />
          {children}
          <Footer />
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
