# Generated by Django 6.0.7 on 2026-07-17 13:08

import django.contrib.postgres.fields
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='staff/')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='academic.department')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.department')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_num', models.PositiveSmallIntegerField(blank=True, help_text='رقم المجموعه', null=True)),
                ('session_type', models.CharField(choices=[('LEC', 'محاضرة'), ('SEC', 'سيكشن')], max_length=3)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('السبت', 'Saturday'), ('الاحد', 'Sunday'), ('الاثنين', 'Monday'), ('الثلاثاء', 'Tuesday'), ('الاربعاء', 'Wednesday'), ('الخميس', 'Thursday')], max_length=20))),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='academic.staffmember')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academic.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExamCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_num', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
