# Generated by Django 6.0.7 on 2026-07-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_staffmember_educator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='educator',
            field=models.BooleanField(default=False, help_text='Indicates wither to hide from collage management or not'),
        ),
        migrations.DeleteModel(
            name='ExamCommittee',
        ),
    ]
