# Generated by Django 6.0.7 on 2026-07-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='educator',
            field=models.BooleanField(default=False),
        ),
    ]
