# Generated by Django 6.0.7 on 2026-07-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_staffmember_educator_delete_examcommittee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
