# Generated by Django 6.0.7 on 2026-07-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='full_description',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
